# -*- coding: utf-8 -*-
{
    'name': "Simple Manufacturing",
    'summary': "إدارة ورشة مقاولات بالاعتماد على مخزون أودو القياسي",
    'description': """
نظام إدارة ورشة مقاولات (نجارة / حدادة / ألمنيوم / CNC) يعتمد على مخزون أودو
القياسي كمصدر وحيد للمخزون (بدون mrp وبدون ازدواجية). دورة مترابطة:
أمر بيع → أمر تصنيع → طلب شراء للناقص → استلام → تصنيع → تسليم → إغلاق المشروع.
""",
    'author': "TECFY",
    'website': "https://www.tecfy.io",
    'category': "Manufacturing",
    'license': "LGPL-3",
    'version': "19.0.13.5.0",
    'depends': ["base", "mail", "sale", "stock"],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'report/report_base.xml',
        'report/report_manufacturing_order.xml',
        'report/report_material_request.xml',
        'report/report_purchase_request.xml',
        'report/report_delivery.xml',
        'report/report_quality_check.xml',
        'report/report_survey.xml',
        'report/report_daily_prep.xml',
        'report/report_daily_report.xml',
        'report/report_attendance.xml',
        'report/report_timecard.xml',
        'report/report_job_order.xml',
        'report/report_ncr.xml',
        'report/report_maintenance.xml',
        'report/report_toolbox.xml',
        'report/report_closeout.xml',
        'report/report_sales_report.xml',
        'views/bom_views.xml',
        'views/manufacturing_order_views.xml',
        'views/purchase_request_views.xml',
        'views/delivery_views.xml',
        'views/material_request_views.xml',
        'views/quality_check_views.xml',
        'views/survey_views.xml',
        'views/daily_ops_views.xml',
        'views/job_order_views.xml',
        'views/attendance_views.xml',
        'views/timecard_views.xml',
        'views/ncr_views.xml',
        'views/maintenance_views.xml',
        'views/toolbox_views.xml',
        'views/closeout_views.xml',
        'views/sales_report_views.xml',
        'views/productivity_report_views.xml',
        'views/sale_order_views.xml',
        'views/company_views.xml',
        'views/menu.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'simple_manufacturing/static/src/js/disable_partner_autocomplete.js',
            'simple_manufacturing/static/src/js/finger_signature.js',
            'simple_manufacturing/static/src/xml/finger_signature.xml',
        ],
    },
    'application': True,
    'installable': True,
}
