from . import test_phase4_core
from . import test_phase5_operations
from . import test_phaseA_classification
from . import test_phaseB_price_intelligence
from . import test_phaseC_import
from . import test_phaseD_budget
from . import test_phaseE_approval
from . import test_phaseF_subcontract
from . import test_phaseH_project_hub
from . import test_phaseI_wbs
