# -*- coding: utf-8 -*-
{
    "name": "رواسي سما — إدارة الإنشاءات والمقاولات",
    "version": "19.0.8.4.2",
    "category": "Services/Project",
    "summary": "موديول إدارة دورة المنافسات والمشاريع الإنشائية (Rawasi Sama Construction ERP)",
    "description": "موديول أودو أصلي يؤتمت الدورة المستندية لشركات المقاولات من الفرصة إلى الإغلاق. المبدأ المعماري: بند جدول الكميات هو النواة الذرية للنظام (BOQ Item is the Atomic Unit). المرحلة صفر: الأساس + الأدوار السبعة + قائمة التطبيق + لوحة التحكم.",
    "author": "Rawasi Sama",
    "website": "https://rawasi-sama.sa",
    "license": "LGPL-3",
    "depends": [
        "base",
        "web",
        "mail",
        "project",
    ],
    "data": [
        "security/rawasi_security.xml",
        "security/ir.model.access.csv",
        "security/multicompany_rules.xml",
        "security/subcontractor_security.xml",
        "data/rawasi_currency_data.xml",
        "data/rawasi_sequence_data.xml",
        "data/rawasi_unit_data.xml",
        "data/rawasi_sbc_code_data.xml",
        "data/rawasi_wbs_phase_data.xml",
        "data/rawasi_cron_data.xml",
        "views/rawasi_competition_views.xml",
        "views/rawasi_project_views.xml",
        "views/rawasi_price_intelligence_views.xml",
        "views/rawasi_config_views.xml",
        "views/boq_import_wizard_views.xml",
        "views/rawasi_wbs_views.xml",
        "views/schedule_import_wizard_views.xml",
        "views/rawasi_procurement_views.xml",
        "report/mas_report.xml",
        "report/rawasi_reports.xml",
        "report/schedule_report.xml",
        "report/subcontractor_reports.xml",
        "views/subcontractor_views.xml",
        "views/subcontract_views.xml",
        "views/subcontract_ipc_views.xml",
        "views/rawasi_document_views.xml",
        "views/rawasi_mas_views.xml",
        "views/rawasi_site_views.xml",
        "views/rawasi_contracts_views.xml",
        "views/rawasi_dashboard_views.xml",
        "views/rawasi_menus.xml",
        "views/subcontractor_menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "rawasi_construction/static/src/dashboard/dashboard.scss",
            "rawasi_construction/static/src/dashboard/dashboard.js",
            "rawasi_construction/static/src/dashboard/dashboard.xml",
        ],
    },
    "application": True,
    "installable": True,
}
